name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          version-file: './package.json,./package-lock.json'
          release-count: 0
      
      - name: Install GitVersion
        run: |
          wget https://github.com/GitTools/GitVersion/releases/download/5.12.0/gitversion-linux-x64-5.12.0.tar.gz
          tar -xzvf gitversion-linux-x64-5.12.0.tar.gz

      - name: Determine version
        run: |
          ./gitversion /config GitVersion.yml /output buildserver
          echo "GitVersion_SemVer=$(cat _version.txt)" >> $GITHUB_ENV

      - name: create release
        run: |
          git tag $GitVersion_SemVer
          git push origin $GitVersion_SemVer\
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        # with:
        #   tag_name: ${{ steps.changelog.outputs.tag }}
        #   release_name: ${{ steps.changelog.outputs.tag }}
        #   body: ${{ steps.changelog.outputs.clean_changelog }}