name: Releases
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-on-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        run: |
          wget https://github.com/GitTools/GitVersion/releases/download/5.12.0/gitversion-linux-x64-5.12.0.tar.gz
          tar -xzvf gitversion-linux-x64-5.12.0.tar.gz

  release-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          version-file: './package.json,./package-lock.json'
          release-count: 0
          bump-minor: true
          config-file-path: .version-bump-rules.js

      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: "v${{ env.GIT_VERSION }}"
          release_name: "v${{ env.GIT_VERSION }}"
          body: ${{ steps.changelog.outputs.clean_changelog }}
